version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    deploy:
      replicas: 1
    ports:
      - '9200:9200'
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    networks:
      - elastic-network
  kibana:
    depends_on:
      - elasticsearch
    image: kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - NODE_OPTIONS= # This is to disable the legacy OpenSSL provider which is enabled by default to prevent breaking changes
    ports:
      - '5601:5601'
    volumes:
      - ./kibana_data:/usr/share/kibana/data
    networks:
      - elastic-network

# Ensure these directories exist first
volumes:
  es_data:
    driver: local
  kibana_data:
    driver: local
networks:
  elastic-network:
